default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: creator_map_development

test:
  <<: *default
  database: creator_map_login_test

production:
  <<: *default
  database: creator_map_production
